#!/bin/sh
#

cat src/class.lua src/component.lua src/entity.lua src/system.lua src/eventManager.lua src/events/componentAdded.lua src/events/componentRemoved.lua src/engine.lua > concat.lua
mkdir -p dist
luamin -f concat.lua > dist/lovetoys-min.lua
git add dist

